### ISSUE TITLE
Working with rows

### ISSUE THREAD

**Issue by caniko** [w2sv/koala#8]
I can't iterate through rows using `koala`, is there any method that I don't know off? `row[idx]` only gives `List<Object?>`

I suggest implementing a row index to map of column name to value method, and using this method to iterate through the dataframe. Unless I am missing something, and there is a better way.

I can make a PR, but I think you'd probably make a better design decision than I will. I can review nonetheless!

**Comment by w2sv** [comment]
There already is the `List<RecordRowMap> rowMaps()` function, which should provide what you're looking for.
